theme: jekyll-theme-dinky

title: <img src="SPRITS_logo.png" width="80%" alt="SPRITS 2018"> SPRITS'18
description: [<ul><li><a href='/sprits/index'>Home</a></li><li><a href='/sprits/cfp'>CfP</a></li><li><a href='/sprits/committee'>Program Committee</a></li></ul>]
