theme: jekyll-theme-hacker

title: <a href='/mif13/2018'>SPRITS 2018</a>
description: [<ul><li><a href='#'>Home</a></li><li><a href='/sprits/cfp'>CfP</a></li><li><a href='/sprits/pc'>Program Committee</a></li></ul>]
